
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-gateway
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

# 网关配置

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false # 停用超时设置
        isolation:
          thread:
            timeoutInMilliseconds: 80000

swagger.enabled: true


apiurl:
  gatewayurl: http://localhost:9000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    sba-account:
      path: /user/**
      serviceId: sba-user
      stripPrefix: false
      sensitiveHeaders:
    sba-auth:
      path: /auth/**
      serviceId: sba-security
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers
    sba-course:
      path: /course/**
      serviceId: sba-course
      stripPrefix: false
      sensitiveHeaders:

